
name: Deploy to AWS EC2 Server "server pr deploy krny wali pipeline"
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    
    name: Deploying to AWS EC2 Production Server "Ec2 pr deploy kry ga"
    runs-on: [ self-hosted, reactapp-runner ]
    environment: Production
    env:
      CONTAINER_NAME: reactapp-test
      IMAGE_NAME_TAG: reactapp-test-image:latest
      HOST_PORT: 3000
      CONTAINER_PORT: 3000

    steps:
      - name: Checkout "branch checkout hogi"
        uses: actions/checkout@v2
        with:
          clean: False

      - name: Building and Assigning Tag to image "image ko bna raha"
        run: |
          docker build -t $IMAGE_NAME_TAG .
      
      - name: Removing old Container if exits "purana container khatm ho jy ga"
        run: |
          docker stop $CONTAINER_NAME || true && docker rm $CONTAINER_NAME || true
      
      - name: Starting Docker Container "docker container chala raha ha"
        run: |
          docker run -d -p $HOST_PORT:$CONTAINER_PORT --restart unless-stopped --name $CONTAINER_NAME  $IMAGE_NAME_TAG
      
      - name: View Docker status "docker ka status show hoga"
        run: |
          docker ps
      
      - name: Cleaning Server "Purrany container or images khatm kry ga"
        run: |
          echo y | docker system prune